version: '3.8'

services:

  db:
    image: 'docker.io/bitnami/mariadb:latest'
    restart: on-failure
    ports:
      - '3306:3306'
    volumes:
      - './data/mariadb_data:/bitnami/mariadb'
    #environment:
      #ALLOW_EMPTY_PASSWORD: yes
    env_file:
      - ./mariadb.env
      # first, test connection:
      # mysql --port=3306 --host=localhost --user=ghost --password='qd120)3JlN(XLN' --protocol=TCP
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

  cms:
    # image: 'docker.io/bitnami/ghost:3-debian-10'
    image: ghost:3-alpine
    restart: unless-stopped 
    ports:
    #  - "8080:8080"
      - '8080:2368'
    volumes:
      - ./data/cms_content/:/var/lib/ghost/content/
    #environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      # see also https://ghost.org/docs/concepts/config/#mail
    env_file:
      - ./ghost.env
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8081"

volumes:
  db_data:
    driver: local
  cms_data:
    driver: local

